# Generated by Django 6.0.5 on 2026-05-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0021_alter_ticket_technician'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='receive_email_notifications',
            field=models.BooleanField(default=True, verbose_name='Получать уведомления по почте'),
        ),
    ]
