# Generated by Django 6.0.5 on 2026-05-05 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_ticket_participants(apps, schema_editor):
    Ticket = apps.get_model('desk', 'Ticket')

    for ticket in Ticket.objects.all():
        participants = []
        if ticket.created_by_id:
            participants.append(ticket.created_by_id)
        if ticket.technician_id and ticket.technician_id not in participants:
            participants.append(ticket.technician_id)
        if participants:
            ticket.participants.add(*participants)


def clear_ticket_participants(apps, schema_editor):
    Ticket = apps.get_model('desk', 'Ticket')

    for ticket in Ticket.objects.all():
        ticket.participants.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0022_userprofile_receive_email_notifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='visible_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body', models.TextField(blank=True, verbose_name='Текст')),
                ('level', models.CharField(choices=[('info', 'Информация'), ('success', 'Успешно'), ('warning', 'Предупреждение')], default='info', max_length=20, verbose_name='Уровень')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Ссылка')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['created_at'],
            },
        ),
        migrations.RunPython(populate_ticket_participants, clear_ticket_participants),
    ]
